Login auth rabbit hole
givtnl/givt-app pull request #1205
Opened 2024-10-23 18:20 UTC by MaikelStuivenberg

2024-10-24 08:57 UTC, MaikelStuivenberg commented
@coderabbitai review

2024-10-24 10:04 UTC, TammiLion commented on lib/features/family/features/login/cubit/family_login_cubit.dart
> +        }
Looks like a nice suggestion @MaikelStuivenberg

2024-10-24 10:07 UTC, TammiLion commented on lib/features/family/features/login/presentation/pages/family_login_sheet.dart
> +    if (loginResult) {
I would not do this here and I would not let the login method return a boolean. The cubit should handle what happens afterwards. I would add a custom navigate event instead. So when login succeeds the cubit emits the custom navigate event. The view just handles the custom events but is "unaware" of login logic.

2024-10-24 10:13 UTC, TammiLion requested changes
see comments

2024-10-24 17:29 UTC, MaikelStuivenberg commented on lib/features/family/features/login/cubit/family_login_cubit.dart
> +        }
thanks @coderabbitait! :)

2024-10-28 09:17 UTC, TammiLion commented on lib/features/family/features/login/presentation/models/family_login_sheet_custom.dart
> +///
Misses succes scenario in comment and emitCustom instead of EmitCustom

2024-10-28 09:18 UTC, TammiLion commented on lib/features/family/features/login/cubit/family_login_cubit.dart
> +      final errorDialogs = {
I would make it a field outside of the method. Now everytime you get into the catch method this gets reassigned while it never changes which is inefficient.

2024-10-28 09:59 UTC, TammiLion approved these changes
Approved but checkout the bug in slack!

2024-10-28 12:08 UTC, merged